### ISSUE TITLE
A few mistakes in discovr_13

### ISSUE THREAD

**Issue by kuba58426** [profandyfield/discovr#10]
There are a few mistakes in `discovr_13`:

1. One of the hints in the Exploring data section uses the word "happiness" instead of "attractiveness".
2. I'm not sure if it's a mistake, but "vcov.type = “HC4”" in the main text of Robust models uses typographic quotation marks and thus causes an error if copied and pasted.
1. In the first quiz question in the Transfer task we're asked to "select ALL valid answers" but only one answer can be chosen.
3. In the Transfer task, in coding challenge with simple effects analysis word "console" is repeated twice.
4. Interpretting interactions (level 2) quiz in the Transfer task show statistics' values which I can't find in any of the produced tables but I might not have produced the right tables.

That's a good occasion for me to thank you for "Discovering statistics using R", it's the best book to learn statistics I've encountered. Pitty it wasn't published in my country.

**Comment by profandyfield** [comment]
Hi @kuba58426, thanks for doing that. I've added a comment relating to issue 3. I'll look into issue 5 in due course!

**Comment by profandyfield** [comment]
On 5: The first question relates to the table produced by:

```
xbox_afx <- afex::aov4(injury ~ game*console + (1|id), data = xbox_tib)
xbox_afx
```

The second question relates to the table created by

```
emmeans::joint_tests(xbox_afx, "console")
```
I can't see a problem with the tutorial as such so I'll close this now. Thanks for the feedback.
