### ISSUE TITLE
Inconsistent naming of objects in tutorial on summarizing data

### ISSUE THREAD

**Issue by alexander-hem** [profandyfield/discovr#4]
Just a minor issue: inconsistent naming of objects in tutorial on summarizing data. This is for the "Frequency distributions" section of the tutorial.

![field_discovr_summarizing_data_frequency_dist](https://user-images.githubusercontent.com/74603018/118993786-18565780-b986-11eb-8d8d-7ad073ddbfe0.png)

**Comment by profandyfield** [comment]
Thanks - that's helpful! I've changed this and it'll be reflected in the next patch version (which I plan push to gitHub next week).
